// Real product catalog from CNC Grease & Lubricants.
export const products = [
  { sku: "ELG-181.4-DRUM", name: "Eligate Gel", variant: null, packageType: "Drum", packageSize: 181.4, unit: "KG", unitsPerBox: null, boxesPerSkid: null },
  { sku: "ELG-50-KEG", name: "Eligate Gel", variant: null, packageType: "Keg", packageSize: 50, unit: "KG", unitsPerBox: null, boxesPerSkid: null },
  { sku: "ELG-16-BUCKET", name: "Eligate Gel", variant: null, packageType: "Bucket", packageSize: 16, unit: "KG", unitsPerBox: null, boxesPerSkid: null },
  { sku: "ELG-2", name: "Eligate Gel", variant: null, packageType: "Pack", packageSize: 2, unit: "KG", unitsPerBox: null, boxesPerSkid: null },
  { sku: "ELG-500G", name: "Eligate Gel", variant: null, packageType: "Pack", packageSize: 0.5, unit: "KG", unitsPerBox: null, boxesPerSkid: null },
  { sku: "ELG-400G", name: "Eligate Gel", variant: null, packageType: "Pack", packageSize: 0.4, unit: "KG", unitsPerBox: null, boxesPerSkid: null },
  { sku: "HEC004-50", name: "Hector Grease", variant: "4", packageType: "Keg", packageSize: 50, unit: "KG", unitsPerBox: null, boxesPerSkid: null },
  { sku: "HEC004-16", name: "Hector Grease", variant: "4", packageType: "Bucket", packageSize: 16, unit: "KG", unitsPerBox: null, boxesPerSkid: null },
  { sku: "HEC005-50", name: "Hector Grease", variant: "5", packageType: "Keg", packageSize: 50, unit: "KG", unitsPerBox: null, boxesPerSkid: null },
  { sku: "HEC005-16", name: "Hector Grease", variant: "5", packageType: "Bucket", packageSize: 16, unit: "KG", unitsPerBox: null, boxesPerSkid: null },
  { sku: "GO75-208", name: "Gear Oil", variant: "75W90", packageType: "Drum", packageSize: 208, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "GO75-60", name: "Gear Oil", variant: "75W90", packageType: "Keg", packageSize: 60, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "GO75-19", name: "Gear Oil", variant: "75W90", packageType: "Bucket", packageSize: 19, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "GO80-208", name: "Gear Oil", variant: "80W90", packageType: "Drum", packageSize: 208, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "GO80-60", name: "Gear Oil", variant: "80W90", packageType: "Keg", packageSize: 60, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "GO80-19", name: "Gear Oil", variant: "80W90", packageType: "Bucket", packageSize: 19, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "GO80-5", name: "Gear Oil", variant: "80W90", packageType: "Jug", packageSize: 5, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "SAE50-208", name: "SAE 50HD Oil", variant: null, packageType: "Drum", packageSize: 208, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "SAE50-60", name: "SAE 50HD Oil", variant: null, packageType: "Keg", packageSize: 60, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "SAE50-19", name: "SAE 50HD Oil", variant: null, packageType: "Bucket", packageSize: 19, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "ATF-D3-19", name: "ATF Oil", variant: "D3", packageType: "Bucket", packageSize: 19, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "ATF-D3-5", name: "ATF Oil", variant: "D3", packageType: "Jug", packageSize: 5, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "ATF-D3-1", name: "ATF Oil", variant: "D3", packageType: "Jug", packageSize: 1, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "HYD32-19", name: "Hydraulic Oil", variant: "AW32", packageType: "Bucket", packageSize: 19, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "HYD46-19", name: "Hydraulic Oil", variant: "AW46", packageType: "Bucket", packageSize: 19, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "COOLANT-1000", name: "Coolant", variant: null, packageType: "Tank", packageSize: 1000, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "COOLANT-4.78", name: "Coolant", variant: null, packageType: "Jug", packageSize: 4.78, unit: "L", unitsPerBox: 4, boxesPerSkid: 65 },
  { sku: "WASHER-1000", name: "Washer Fluid", variant: null, packageType: "Tank", packageSize: 1000, unit: "L", unitsPerBox: null, boxesPerSkid: null },
  { sku: "WASHER-4.78", name: "Washer Fluid", variant: null, packageType: "Jug", packageSize: 4.78, unit: "L", unitsPerBox: 4, boxesPerSkid: 65 },
  { sku: "ENG15W40-1000", name: "15W40 Engine Oil", variant: null, packageType: "Tank", packageSize: 1000, unit: "L", unitsPerBox: null, boxesPerSkid: null },
];
